### ISSUE TITLE
Error while calling the test program: FoldFunction can not be a RichFunction. Please use apply(FoldFunction, WindowFunction) instead.

### ISSUE THREAD

**Issue by TjWallas** [vasia/gelly-streaming#18]
(Potentially related to #16 ?)

Hi,

Just tried to clone this repo and run the unit tests using `mvn` (recent master @ f0cc8e1). One test failed due to the error below:

```
Running org.apache.flink.graph.streaming.test.operations.TestSlice
FoldFunction can not be a RichFunction. Please use apply(FoldFunction, WindowFunction) instead.
java.lang.UnsupportedOperationException: FoldFunction can not be a RichFunction. Please use apply(FoldFunction, WindowFunction) instead.
        at org.apache.flink.streaming.api.datastream.WindowedStream.fold(WindowedStream.java:183)
        at org.apache.flink.graph.streaming.GraphWindowStream.foldNeighbors(GraphWindowStream.java:63)
        at org.apache.flink.graph.streaming.test.operations.TestSlice.testFoldNeighborsDefault(TestSlice.java:77)
        at org.apache.flink.graph.streaming.test.operations.TestSlice.testProgram(TestSlice.java:59)
        at org.apache.flink.streaming.util.StreamingProgramTestBase.testJob(StreamingProgramTestBase.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.296 sec <<< FAILURE!

Results :

Failed tests:   testJob(org.apache.flink.graph.streaming.test.operations.TestSlice): Error while calling the test program: FoldFunction can not be a RichFunction. Please use apply(FoldFunction, WindowFunction) instead.
```

Java version:

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

OS:

```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise
```

**Comment by Zainab-Abbas** [comment]
Hi 

Thanks for mentioning the error, we have reproduced the error, soon it will be fixed.

**Comment by vasia** [comment]
Thanks for reporting @TjWallas! It should be fixed now :)
