### ISSUE TITLE
How to run GellyStream on Flink

### ISSUE THREAD

**Issue by lilicao701** [vasia/gelly-streaming#34]
Hi
 I want to test GellyStream's examples on Flink environment, Flink version is 1.2.0, java is java8, operator system is RedHat, but  with the error, and can't successful (local model and cluster model also error).
the error is like flink can't run with java-8, 

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The program's entry point class 'org.apache.flink.graph.streaming.example.ExactTriangleCount' could not be loaded due to a linkage failure.
	at org.apache.flink.client.program.PackagedProgram.loadMainClass(PackagedProgram.java:625)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:198)
	at org.apache.flink.client.CliFrontend.buildProgram(CliFrontend.java:890)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:228)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:1073)
	at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1120)
	at org.apache.flink.client.CliFrontend$2.call(CliFrontend.java:1117)
	at org.apache.flink.runtime.security.HadoopSecurityContext$1.run(HadoopSecurityContext.java:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:40)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1116)
Caused by: java.lang.UnsupportedClassVersionError: org/apache/flink/graph/streaming/example/ExactTriangleCount : Unsupported major.minor version 52.0

**Comment by vasia** [comment]
Hi @lilicao701,
I think this error indicates a Java version mismatch. Can you please check that you have complied the example with the same version as the one in the JVM where you try to load it?

**Comment by lilicao701** [comment]
@vasia 
  I see the Flink-root-client logs, and find the  cause of the error is Flink's config.sh specified JAVA_HOME is not java-1.8
